version: "3.7"
name: tib-production
services:
  rabbitmq:
    image: rabbitmq
    networks:
      - rabbitmq
    ports:
      - 5672:5672
    

  api_gateway: 
    env_file:
      - ./apps/api-gateway/.env
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: production
    networks:
      - rabbitmq
    depends_on:
      - user_service
      - idea_service
      - notification_service
      - wallet_service
      - rabbitmq
    restart: always
    ports:
      - 6001:6001

  user_service:
    build:
      context: .
      dockerfile: ./apps/user-service/Dockerfile
      target: production
    env_file:
      - ./apps/user-service/.env
    networks:
      - rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always

  file_service:
    build:
      context: .
      dockerfile: ./apps/file-service/Dockerfile
      target: production
    env_file:
      - ./apps/file-service/.env
    networks:
      - rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
    ports:
      - 6100:6100

  wallet_service:
    build:
      context: .
      dockerfile: ./apps/wallet-service/Dockerfile
      target: production
    env_file:
      - ./apps/wallet-service/.env
    networks:
      - rabbitmq
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy

  idea_service:
    build:
      context: .
      dockerfile: ./apps/idea-service/Dockerfile
      target: production
    env_file:
      - ./apps/idea-service/.env
    networks:
      - rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always

  notification_service:
    build:
      context: .
      dockerfile: ./apps/notification-service/Dockerfile
      target: production
    env_file:
      - ./apps/notification-service/.env
    networks:
      - rabbitmq
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - 6200:6200

networks:
  rabbitmq:
    driver: bridge

volumes:
  pgadmin-data:
  file_storage:
