version: "3.7"
services:
  rabbitmq:
    image: rabbitmq
    networks:
      - rabbitmq
    ports:
      - 5672:5672

  api_gateway: 
    env_file:
      - ./apps/api-gateway/.env
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    networks:
      - rabbitmq
    depends_on:
      - user_service
      - rabbitmq
    ports:
      - 5000:5000

  user_service:
    build:
      context: .
      dockerfile: ./apps/user-service/Dockerfile
      target: development
    env_file:
      - ./apps/user-service/.env
    networks:
      - postgres
      - rabbitmq
    depends_on:
      - user_db
      - rabbitmq
    volumes:
      - .:/usr/src/app

  user_db:
    image: postgres:latest
    networks:
      - postgres
    ports:
      - 5432:5432
    volumes:
      - user_db:/data/postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tib_user_db

  pgadmin:
    image: dpage/pgadmin4:6.18
    networks:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@tib.com
      - PGADMIN_DEFAULT_PASSWORD=admin

networks:
  postgres:
    driver: bridge
  rabbitmq:
    driver: bridge

volumes:
  user_db:
  pgadmin-data:
