version: "3.7"
services:
  rabbitmq:
    image: rabbitmq
    networks:
      - rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      start_period: 120s
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 5672:5672

  api_gateway: 
    env_file:
      - ./apps/api-gateway/.env
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    networks:
      - rabbitmq
    depends_on:
      user_service: 
        condition: service_started
      rabbitmq:
        condition: service_healthy
    ports:
      - 6001:6001

  user_service:
    build:
      context: .
      dockerfile: ./apps/user-service/Dockerfile
      target: development
    env_file:
      - ./apps/user-service/.env
    networks:
      - postgres
      - rabbitmq
    depends_on:
      user_db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    volumes:
      - .:/usr/src/app

  user_db:
    image: postgres:latest
    networks:
      - postgres
    ports:
      - 5432:5432
    volumes:
      - user_db:/data/postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tib_user_db

  file_service:
    build:
      context: .
      dockerfile: ./apps/file-service/Dockerfile
      target: development
    env_file:
      - ./apps/file-service/.env
    networks:
      - postgres
      - rabbitmq
    depends_on:
      file_db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    volumes:
      - file_storage:/usr/src/app
    ports:
      - 6100:6100

  file_db:
    image: postgres:latest
    networks:
      - postgres
    ports:
      - 5433:5432
    volumes:
      - file_db:/data/postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tib_file_db

  wallet_service:
    build:
      context: .
      dockerfile: ./apps/wallet-service/Dockerfile
      target: development
    env_file:
      - ./apps/wallet-service/.env
    networks:
      - postgres
      - rabbitmq
    depends_on:
      wallet_db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    volumes:
      - .:/usr/src/app

  wallet_db:
    image: postgres:latest
    networks:
      - postgres
    ports:
      - 5434:5432
    volumes:
      - wallet_db:/data/postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tib_wallet_db

  idea_service:
    build:
      context: .
      dockerfile: ./apps/idea-service/Dockerfile
      target: development
    env_file:
      - ./apps/idea-service/.env
    networks:
      - postgres
      - rabbitmq
    depends_on:
      idea_db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    volumes:
      - .:/usr/src/app

  idea_db:
    image: postgres:latest
    networks:
      - postgres
    ports:
      - 5435:5432
    volumes:
      - idea_db:/data/postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tib_idea_db

  notification_service:
    build:
      context: .
      dockerfile: ./apps/notification-service/Dockerfile
      target: development
    env_file:
      - ./apps/notification-service/.env
    networks:
      - rabbitmq
      - postgres
    depends_on:
      notification_db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    ports:
      - 6200:6200

  notification_db:
    image: postgres:latest
    networks:
      - postgres
    ports:
      - 5436:5432
    volumes:
      - notification_db:/data/postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tib_notification_db

  pgadmin:
    image: dpage/pgadmin4:6.18
    networks:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@tib.com
      - PGADMIN_DEFAULT_PASSWORD=admin

networks:
  postgres:
    driver: bridge
  rabbitmq:
    driver: bridge

volumes:
  user_db:
  file_db:
  wallet_db:
  idea_db:
  notification_db:
  pgadmin-data:
  file_storage:
